// hc_ruin — introduce channel defects into HamChannel PCM sample data.
//
// Reads f64le PCM (mono, 48 kHz) from a file (last argument) or stdin,
// applies three impairment stages in order, and writes f64le PCM to stdout
// or to -o <filename>:
//
//   Stage 1 — FADING. Rician/Rayleigh amplitude fading generated by a
//   Jakes-style sum of 16 complex oscillators.
//       --fade-rate <Hz>   maximum fading (Doppler) rate; 0 = off (default)
//       --fade-k <K>       Rician K-factor, linear power ratio of the
//                          steady path to the scattered paths.
//                          0 = pure Rayleigh (deep fades), larger = milder.
//                          (default 1.0)
//
//   Stage 2 — GAUSSIAN NOISE.
//       --snr <dB>         add white Gaussian noise at this SNR relative to
//                          the RMS of the (faded) signal
//       --noise <rms>      ... or give the noise RMS directly
//                          (neither = no noise)
//
//   Stage 3 — PHASE NOISE (sampling jitter). The signal is upsampled and
//   interpolated 16x; each output sample is then taken from a position
//   within its 16-sample set chosen by a first-order (AR-1) phase-noise
//   process, downsampling back to 48 kHz. Nominal position is the set
//   centre (a fixed 1/2-sample delay); the jitter is bounded to the set.
//       --pn-sigma <s>     RMS jitter in 1/16-sample steps (0 = off,
//                          default; 16 = one full sample would be huge)
//       --pn-corr <n>      jitter correlation time in samples
//                          (default 48 = 1 ms)
//
//   Common:
//       --seed <n>         PRNG seed (default 1; same seed = same channel)
//       -o <file>          write output here instead of stdout
//
// Example — full pipeline:
//   hc_gen -m "test" | hc_ruin --fade-rate 2 --fade-k 4 --snr 10 \
//       --pn-sigma 3 | hc_info

import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

Never _usage(int code) {
  final out = code == 0 ? stdout : stderr;
  out.writeln('usage: hc_ruin [--fade-rate Hz] [--fade-k K]\n'
      '               [--snr dB | --noise rms]\n'
      '               [--pn-sigma s16] [--pn-corr samples]\n'
      '               [--seed n] [-o <file>] [<input.f64>]\n'
      '       (reads stdin when no filename is given)');
  exit(code);
}

const sampleRate = 48000;

Future<void> main(List<String> argv) async {
  var fadeRate = 0.0;
  var fadeK = 1.0;
  double? snrDb;
  double? noiseRms;
  var pnSigma = 0.0;
  var pnCorr = 48.0;
  var seed = 1;
  String? outPath;
  String? inPath;

  double nextD(int i) {
    if (i + 1 >= argv.length) _usage(2);
    final v = double.tryParse(argv[i + 1]);
    if (v == null) _usage(2);
    return v;
  }

  for (var i = 0; i < argv.length; i++) {
    switch (argv[i]) {
      case '--help' || '-h':
        _usage(0);
      case '--fade-rate':
        fadeRate = nextD(i++);
      case '--fade-k':
        fadeK = nextD(i++);
      case '--snr':
        snrDb = nextD(i++);
      case '--noise':
        noiseRms = nextD(i++);
      case '--pn-sigma':
        pnSigma = nextD(i++);
      case '--pn-corr':
        pnCorr = nextD(i++);
      case '--seed':
        seed = nextD(i++).toInt();
      case '-o' || '--output':
        if (i + 1 >= argv.length) _usage(2);
        outPath = argv[++i];
      default:
        if (argv[i].startsWith('-')) {
          stderr.writeln('unknown option: ${argv[i]}');
          _usage(2);
        }
        inPath = argv[i];
    }
  }
  if (snrDb != null && noiseRms != null) {
    stderr.writeln('hc_ruin: give --snr or --noise, not both');
    exit(2);
  }

  // ---- read input ----
  final Uint8List inBytes;
  if (inPath == null) {
    final bb = BytesBuilder(copy: false);
    await for (final chunk in stdin) {
      bb.add(chunk);
    }
    inBytes = bb.takeBytes();
  } else {
    final f = File(inPath!);
    if (!f.existsSync()) {
      stderr.writeln('hc_ruin: no such file: $inPath');
      exit(1);
    }
    inBytes = f.readAsBytesSync();
  }
  final n = inBytes.length ~/ 8;
  final bd = ByteData.sublistView(inBytes);
  var x = Float64List(n);
  for (var i = 0; i < n; i++) {
    x[i] = bd.getFloat64(i * 8, Endian.little);
  }

  final rng = math.Random(seed);
  double gauss() {
    final u1 = math.max(rng.nextDouble(), 1e-12);
    final u2 = rng.nextDouble();
    return math.sqrt(-2 * math.log(u1)) * math.cos(2 * math.pi * u2);
  }

  final applied = <String>[];

  // ---- stage 1: fading ----
  if (fadeRate > 0) {
    // Jakes-style scattered component: 16 complex oscillators at Doppler
    // frequencies fd*cos(alpha), random phases, advanced by complex
    // rotation (no per-sample trig). E|h|^2 = 1.
    const nOsc = 16;
    final oscRe = Float64List(nOsc), oscIm = Float64List(nOsc);
    final rotRe = Float64List(nOsc), rotIm = Float64List(nOsc);
    for (var k = 0; k < nOsc; k++) {
      final alpha = 2 * math.pi * (k + 0.5) / nOsc + rng.nextDouble() * 0.1;
      final f = fadeRate * math.cos(alpha);
      final w = 2 * math.pi * f / sampleRate;
      rotRe[k] = math.cos(w);
      rotIm[k] = math.sin(w);
      final phi = rng.nextDouble() * 2 * math.pi;
      oscRe[k] = math.cos(phi);
      oscIm[k] = math.sin(phi);
    }
    final steady = math.sqrt(fadeK / (fadeK + 1));
    final scatter = math.sqrt(1.0 / (fadeK + 1) / nOsc);
    for (var i = 0; i < n; i++) {
      var hr = 0.0, hi = 0.0;
      for (var k = 0; k < nOsc; k++) {
        final r = oscRe[k] * rotRe[k] - oscIm[k] * rotIm[k];
        final im = oscRe[k] * rotIm[k] + oscIm[k] * rotRe[k];
        oscRe[k] = r;
        oscIm[k] = im;
        hr += r;
        hi += im;
      }
      final cr = steady + scatter * hr;
      final ci = scatter * hi;
      x[i] *= math.sqrt(cr * cr + ci * ci);
    }
    applied.add('fading rate=${fadeRate}Hz K=$fadeK');
  }

  // ---- stage 2: gaussian noise ----
  if (snrDb != null || noiseRms != null) {
    double sigma;
    if (noiseRms != null) {
      sigma = noiseRms!;
    } else {
      var p = 0.0;
      for (final v in x) {
        p += v * v;
      }
      final rms = n == 0 ? 0.0 : math.sqrt(p / n);
      sigma = rms * math.pow(10, -snrDb! / 20);
      applied.add('noise snr=${snrDb}dB (sigma=${sigma.toStringAsFixed(6)})');
    }
    if (noiseRms != null) applied.add('noise rms=$sigma');
    for (var i = 0; i < n; i++) {
      x[i] += sigma * gauss();
    }
  }

  // ---- stage 3: phase noise via 16x oversampled sample selection ----
  if (pnSigma > 0) {
    // Each output sample n is taken from the 16x-upsampled stream at
    // position 16n + j, j in 0..15, nominal 8 (the set centre). j follows
    // an AR-1 process with stationary RMS --pn-sigma (in 1/16 steps) and
    // correlation time --pn-corr samples. The 16x interpolation uses a
    // Catmull-Rom kernel evaluated polyphase-style at pos/16.
    final rho = pnCorr <= 0 ? 0.0 : math.exp(-1.0 / pnCorr);
    final drive = pnSigma * math.sqrt(math.max(1 - rho * rho, 1e-12));
    var w = 0.0;
    final y = Float64List(n);
    double at(int i) => (i < 0 || i >= n) ? 0.0 : x[i];
    for (var i = 0; i < n; i++) {
      w = rho * w + drive * gauss();
      final j = (8 + w.round()).clamp(0, 15);
      final pos = i + j / 16.0;
      final i1 = pos.floor();
      final t = pos - i1;
      final p0 = at(i1 - 1), p1 = at(i1), p2 = at(i1 + 1), p3 = at(i1 + 2);
      // Catmull-Rom cubic interpolation.
      y[i] = 0.5 *
          ((2 * p1) +
              (-p0 + p2) * t +
              (2 * p0 - 5 * p1 + 4 * p2 - p3) * t * t +
              (-p0 + 3 * p1 - 3 * p2 + p3) * t * t * t);
    }
    x = y;
    applied.add('phase-noise sigma=$pnSigma/16 corr=${pnCorr}smp');
  }

  // ---- write output ----
  final outBytes = Uint8List(n * 8);
  final obd = ByteData.sublistView(outBytes);
  for (var i = 0; i < n; i++) {
    obd.setFloat64(i * 8, x[i], Endian.little);
  }
  if (outPath != null) {
    File(outPath!).writeAsBytesSync(outBytes);
  } else {
    stdout.add(outBytes);
    await stdout.flush();
  }

  stderr.writeln('hc_ruin: $n samples '
      '(${(n / sampleRate).toStringAsFixed(2)} s) '
      '${applied.isEmpty ? 'passthrough (no impairments requested)' : applied.join(' · ')}'
      '${outPath != null ? ' -> $outPath' : ' -> stdout'} [seed $seed]');
}
